sudo: false
language: perl
perl:
- 5.18
deploy:
  provider: heroku
  app: bgimg-3746
  api_key:
    secure: PTayu8r4CNY80KRxBgzQzcWaeZjrxvlMj2i3Dke7TjJTTg6s603DHjc6t0n9oSTPS8CS9Uwp3vck+pBL4eDkZMrfTRu1oPAIWUJhC5gqXAdlO1OUGdPCyvCuy2oveAdlMLlDsTTde0izw6dXinTh9hYQeoDNNCIq/mXwEnWpvvqiQisBTCvo9Fq7X85zYL31jM8NPa0kGNthp3CIZKhl6S07lNw8oR5aSMMgO6k+ZyeuJhdtJRlM6GBpijufIkaToLymyoylArEBK+RKiNsbFTHV+X2ZGnsT25AbCdf6GvtdRiNUwYjP/oe7+epYtXOi1C/GWGU2n3vsDn9qH2UnugOH51MjpnXVK/kSf/Vo3i9f3v8UC7+6dMVitBhY3BpVsp0nWFO+M00KUtYZYX5k8Dm04gtPLWhGA7fQBliLR49JqbD5RvV4mhv96MBonOFI60X8OjGQWQc9RaIxr4awaeMSQyO5nA+uTjNqRRLt8Ea8B20OTysdb3oDt6vovjzGDGoHx0tAhnpXdO0xsofOxR89b4yRFIr0Q6D+VSNI8trRDsnQV+hs9hoI4/g0C4mpgrkLZUsM3ZmXBrk+PcaaCGwMhPl0fAdDx1ChQbcdyH/I2jNFgFI72xa0w+tn/yotpo0YnRRqt3/EeVPjrVTeeTSI3+5L6ukrl6qsmAarMY8=
