#!/bin/sh
export PATH="/app/vendor/perl/bin:/app/vendor/perl-deps/bin:$PATH"
export PERL5OPT="-Mlocal::lib=/app/vendor/perl-deps"
echo "PATH: $PATH, PERL5OPT: $PERL5OPT"
perl $(which starman) --preload-app --port $PORT
